package com.example.hien_android_final.api

data class CoinDataItem(
    val ath: Int,
    val ath_change_percentage: Double,
    val ath_date: String,
    val atl: Int,
    val atl_change_percentage: Double,
    val atl_date: String,
    val circulating_supply: Double,
    val current_price: Int,
    val fully_diluted_valuation: Long,
    val high_24h: Int,
    val id: String,
    val image: String,
    val last_updated: String,
    val low_24h: Int,
    val market_cap: Long,
    val market_cap_change_24h: Long,
    val market_cap_change_percentage_24h: Double,
    val market_cap_rank: Int,
    val max_supply: Int,
    val name: String,
    val price_change_24h: Int,
    val price_change_percentage_24h: Double,
    val roi: Roi,
    val symbol: String,
    val total_supply: Double,
    val total_volume: Long
)